services:
  strapi:
    build: ./server
    ports:
      - "1337:1337"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      STRAPI_ADMIN_BUILD_SKIP: "true"

  nuxt:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    environment:
      NUXT_PUBLIC_STRAPI_URL: http://strapi:1337